[theme]
base="light"
primaryColor="#004aad"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#000000"
font="sans serif"

[server]
headless = true
enableCORS = false
port = 8080
